CREATE OR REPLACE ROLE "KRIS_TEST_ROLE";
GRANT ROLE "KRIS_TEST_ROLE" TO ROLE "PUBLIC";

CREATE OR REPLACE USER KRIS_TEST PASSWORD = '12345' DEFAULT_ROLE = "KRIS_TEST_ROLE" DEFAULT_WAREHOUSE = 'KRISTEST_WH' DEFAULT_NAMESPACE = 'KRIS' MUST_CHANGE_PASSWORD = FALSE;
GRANT ROLE "KRIS_TEST_ROLE" TO USER KRIS_TEST;

DROP USER KRIS_TEST;
DROP ROLE KRIS_TEST_ROLE;

-- log IN AS KRIS_TEST
-- AND run CREATE TABLE

CREATE TABLE "DEMO_DB"."KRISTEST"."TEST1" ("C1" STRING);